### ISSUE TITLE
添加技能导致的bug

### ISSUE THREAD

**Issue by caibingcheng** [muddery/muddery#13]
两种情况：

1.  先建角色（玩家），再设置并添加技能，出错（玩家该角色无法使用）；
2.  先设置并添加技能，在建角色，可以正常使用。

请问这是不是一个设计失误，还是系统本身就是这样设计的呢？如果把技能改为物品或NPC之类，则第一种情况不会发生

**Comment by luyijun** [comment]
把服务器停掉然后重启，角色重新登录就可以看到新加的技能了。
在线添加技能还有些问题，客户端会缓存旧数据的，这个我考虑一下怎么解决。
