### ISSUE TITLE
pip install -e muddery failed

### ISSUE THREAD

**Issue by punkmonday** [muddery/muddery#26]
ERROR: Command errored out with exit status 1: 'C:\Users\ASUS\scoop\apps\anaconda3\current\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ASUS\\AppData\\Local\\Temp\\pip-install-nm8lu09x\\twisted_823d66549e404e348a567b017afb7e29\\setup.py'"'"'; __file__='"'"'C:\\Users\\ASUS\\AppData\\Local\\Temp\\pip-install-nm8lu09x\\twisted_823d66549e404e348a567b017afb7e29\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ASUS\AppData\Local\Temp\pip-record-a9p2ts2b\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\ASUS\scoop\apps\anaconda3\current\Include\twisted' Check the logs for full command output.

**Comment by luyijun** [comment]
你好，这看上去是Twisted安装失败了，Windows里安装Twisted会遇到一些问题的，请把执行的命令和报错的信息贴全。可以加入QQ群 230774532 详细讨论。
